### ISSUE TITLE
Support lite-mode

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-starknet#55]
### Overview

Support devnet lite mode

### Specification

* Allow settings in `ape-config.yaml`:

```yaml
starknet:
  provider:
    lite_mode: True  # Defaults to False
```

And then set the CLI flag accordingly.

Could also make work in `change_settings()`

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
